### ISSUE TITLE
plugin crashes

### ISSUE THREAD

**Issue by turnermm** [proxymus/note_ckgdoku#1]
I'm afraid your plugin crashed my toolbar.  I'd like to see it working.

**Comment by proxymus** [comment]
I was not able to reproduce it. I'm using the latest CKGdoku farm version with a dokuwiki farm. Can you try it with that version? I will setup a new dokuwiki (without farms) next week and then I will try to reproduce the issue.

**Comment by proxymus** [comment]
I've noticed that there was a missing comma in the english language file. Maybe this has caused your issue. Can you try it again?

**Comment by turnermm** [comment]
See  pull: https://github.com/proxymus/note_ckgdoku/pull/2
